import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { Plus, X, Image as ImageIcon } from 'lucide-react';
import { esgAPI, uploadAPI } from '../services/api';
import { useAdmin } from '../context/AdminAuth';
import DataTable from '../components/UI/DataTable';

const TYPES = ['report', 'rating', 'news', 'insight'];
const emptyForm = { title:'', type:'report', description:'', content:'', coverImage:'', documentUrl:'', tags:[], isPublished:true };
const tagsFrom = v => Array.isArray(v) ? v : String(v || '').split(',').map(x=>x.trim()).filter(Boolean);

export default function ESGManager({ addToast }) {
  const { user } = useAdmin();
  const [reports,setReports]=useState([]); const [loading,setLoading]=useState(true); const [editing,setEditing]=useState(null); const [modalOpen,setModalOpen]=useState(false); const [uploading,setUploading]=useState(false); const [form,setForm]=useState(emptyForm);
  const load=async()=>{setLoading(true);try{const res=await esgAPI.getAdminAll('?limit=100');setReports(res.data||[])}catch(e){addToast?.(e.message,'error')}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const edit=r=>{setEditing(r);setForm({...emptyForm,...r,tags:Array.isArray(r.tags)?r.tags.join(', '):''});setModalOpen(true)};
  const submit=async e=>{e.preventDefault();const payload={...form,tags:tagsFrom(form.tags)};try{if(editing){await esgAPI.update(editing._id,payload);addToast?.('ESG report updated','success')}else{await esgAPI.create(payload);addToast?.('ESG report created','success')}setModalOpen(false);setEditing(null);setForm({...emptyForm});load()}catch(err){addToast?.(err.message,'error')}};
  const remove=async r=>{if(!window.confirm(`Delete "${r.title}"?`))return;try{await esgAPI.delete(r._id);addToast?.('ESG report deleted','success');load()}catch(e){addToast?.(e.message,'error')}};
  const upload=async e=>{const file=e.target.files?.[0];if(!file)return;setUploading(true);try{const res=await uploadAPI.uploadImage(file);setForm(f=>({...f,coverImage:res.data.url}));addToast?.('Image uploaded','success')}catch(err){addToast?.(err.message,'error')}finally{setUploading(false)}};
  const columns=[{key:'title',label:'Title'},{key:'type',label:'Type',render:v=><span className="capitalize">{v}</span>},{key:'publishedAt',label:'Date',render:v=>v?new Date(v).toLocaleDateString():'-'},{key:'isPublished',label:'Status',render:v=><span className={`px-2 py-1 rounded text-xs ${v?'bg-green-100 text-green-700':'bg-amber-100 text-amber-700'}`}>{v?'Published':'Draft'}</span>}];
  return <div className="space-y-6"><div className="flex items-center justify-between"><h1 className="text-2xl font-bold text-gray-900">ESG Manager</h1><button onClick={()=>{setEditing(null);setForm({...emptyForm});setModalOpen(true)}} className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"><Plus size={18}/> New ESG Item</button></div><DataTable data={reports} columns={columns} onEdit={edit} onDelete={user?.role==='admin'?remove:undefined} loading={loading} pageSize={8}/>
  {modalOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><motion.div initial={{scale:.95,opacity:0}} animate={{scale:1,opacity:1}} className="bg-white rounded-2xl shadow-2xl w-full max-w-3xl max-h-[90vh] overflow-y-auto p-6"><div className="flex justify-between mb-6"><h2 className="text-xl font-bold">{editing?'Edit ESG Item':'New ESG Item'}</h2><button onClick={()=>setModalOpen(false)} className="p-2 hover:bg-gray-100 rounded-lg"><X size={20}/></button></div><form onSubmit={submit} className="space-y-4"><div className="grid grid-cols-2 gap-4"><Field label="Title" required value={form.title} onChange={v=>setForm({...form,title:v})}/><div><label className="block text-sm font-medium text-gray-700 mb-1">Type</label><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200">{TYPES.map(t=><option key={t}>{t}</option>)}</select></div></div><Field label="Description" required value={form.description} onChange={v=>setForm({...form,description:v})}/><div><label className="block text-sm font-medium text-gray-700 mb-1">Content</label><textarea required value={form.content} onChange={e=>setForm({...form,content:e.target.value})} className="w-full px-4 py-2 rounded-lg border border-gray-200 min-h-40"/></div><div><label className="block text-sm font-medium text-gray-700 mb-1">Cover Image</label><div className="flex gap-2"><input value={form.coverImage} onChange={e=>setForm({...form,coverImage:e.target.value})} className="flex-1 px-4 py-2 rounded-lg border border-gray-200" placeholder="https://..."/><label className="flex items-center gap-2 px-3 bg-gray-100 rounded-lg cursor-pointer"><ImageIcon size={17}/>{uploading?'...':'Upload'}<input type="file" accept="image/*" className="hidden" onChange={upload}/></label></div>{form.coverImage&&<img src={form.coverImage} alt="Cover preview" className="mt-2 h-20 object-cover rounded-lg"/>}</div><Field label="Document URL" value={form.documentUrl} onChange={v=>setForm({...form,documentUrl:v})}/><Field label="Tags (comma separated)" value={form.tags} onChange={v=>setForm({...form,tags:v})}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isPublished} onChange={e=>setForm({...form,isPublished:e.target.checked})}/> Published on website</label><div className="flex justify-end gap-3 pt-4"><button type="button" onClick={()=>setModalOpen(false)} className="px-4 py-2 rounded-lg hover:bg-gray-100">Cancel</button><button type="submit" className="px-6 py-2 bg-blue-600 text-white rounded-lg">{editing?'Update':'Create'}</button></div></form></motion.div></div>}
  </div>;
}
function Field({label,value,onChange,required}){return <div><label className="block text-sm font-medium text-gray-700 mb-1">{label}</label><input required={required} value={value??''} onChange={e=>onChange(e.target.value)} className="w-full px-4 py-2 rounded-lg border border-gray-200 focus:border-blue-500 outline-none"/></div>}
